### ISSUE TITLE
bytes should convert to str

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Nettacker#129]
Hey,

I was testing the framework on a VM, and found this error.

```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/root/owasp-nettacker/lib/scan/wappalyzer/engine.py", line 162, in analyze
    obj = json.loads(pkg_resources.resource_string(__name__, "apps.json"))
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
As it looks, we forget to convert bytes to str to prevent error in Python 3.

Regards.
_________________
**OS**: `CentOS`

**OS Version**: `6.5`

**Python Version**: `3.4.5`

**Comment by pradeepjairamani** [comment]
Hello,

This issue is already there #94 

Best Regards

**Comment by Ali-Razmjoo** [comment]
thanks.
