### ISSUE TITLE
Error in log.py while updating modules to new info messages structure

### ISSUE THREAD

**Issue by pradeepjairamani** [zdresearch/OWASP-Nettacker#165]
Got this error while adding new info to modules
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/OWASP-Nettacker/core/attack.py", line 95, in start_attack
    verbose_level, socks_proxy, retries, methods_args, scan_id, scan_cmd)
  File "/root/OWASP-Nettacker/lib/vuln/xdebug_rce/engine.py", line 160, in start
    'CATEGORY': "scan", 'SCAN_ID': scan_id, 'SCAN_CMD': scan_cmd}, log_in_file, language)
  File "/root/OWASP-Nettacker/core/alert.py", line 95, in info
    __log_into_file(thread_tmp_filename, "w", "0", language)
  File "/root/OWASP-Nettacker/core/log.py", line 219, in __log_into_file
    submit_logs_to_db(language, data)
  File "/root/OWASP-Nettacker/database/db.py", line 163, in submit_logs_to_db
    host=log["HOST"], date=log["TIME"], port=log["PORT"], type=log["TYPE"], category=log["CATEGORY"],
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by Ali-Razmjoo** [comment]
Hi,

thanks for reporting, here is a little more details, this problem is coming from `__log_into_file()` when the condition lead the code to `submit_logs_to_db(language, data)` and the data is not `JSON` structure (for instance: `__log_into_file(thread_tmp_filename, 'w', '1', language)` and thread_tmp_filename is not True in this condition `if _builder(_paths(), default_paths())["tmp_path"] in filename:`).


```python
def __log_into_file(filename, mode, data, language, final=False):
    """
    write a content into a file (support unicode) and submit logs in database. if final=False its writing log in
    the database.

    Args:
        filename: the filename
        mode: writing mode (a, ab, w, wb, etc.)
        data: content
        language: language
        final: True if it's final report otherwise False (default False)

    Returns:
        True if success otherwise None
    """
    if version() is 2:

        if _builder(_paths(), default_paths())["tmp_path"] in filename:
            if not final:
                flock = lockfile.FileLock(filename)
                flock.acquire()
            with open(filename, mode) as save:
                save.write(data + '\n')
            if not final:
                flock.release()
        else:
            if final:
                with open(filename, mode) as save:
                    save.write(data + '\n')
            else:
                submit_logs_to_db(language, data)

    else:

        if _builder(_paths(), default_paths())["tmp_path"] in filename:
            if not final:
                flock = lockfile.FileLock(filename)
                flock.acquire()
            with open(filename, mode, encoding='utf-8') as save:
                save.write(data + '\n')
            if not final:
                flock.release()
        else:
            if final:
                with open(filename, mode, encoding='utf-8') as save:
                    save.write(data + '\n')
            else:
                submit_logs_to_db(language, data)
    return True
```

**Comment by shaddygarg** [comment]
@Ali-Razmjoo, should I write a try catch in the database code to give erroneous message if this is done?

**Comment by Ali-Razmjoo** [comment]
I think we need a better solution, maybe we can check if the data type is JSON/event or not?
