### ISSUE TITLE
Value error while installing 

### ISSUE THREAD

**Issue by mzfr** [zdresearch/OWASP-Nettacker#190]
After installing all the requirements, when I tried to run the setup.py with `python setup.py install` the process stops with the following error

```
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    else "scripts/nettacker", "nettacker.py"]  # script files for windows and other OS
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mzfr/dev/OWASP-Nettacker/venv/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/mzfr/dev/OWASP-Nettacker/venv/lib/python3.5/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mzfr/dev/OWASP-Nettacker/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/mzfr/dev/OWASP-Nettacker/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/mzfr/dev/OWASP-Nettacker/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/mzfr/dev/OWASP-Nettacker/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```
_________________
**OS**: `Manjaro`

**OS Version**: `4.20`

**Python Version**: `3.5`

**Comment by securestep9** [comment]
known issue with Python 3.5 due to incompatible dependencies. A workaround is to use Python 3.6+.
